Repository cmseaton42/node-ethernet-ip, pull requests merged in 2018-03, with the labels that each got.

#3 [1.1.0 beta] Adds task queue class to handle multiple calls of the same CIP service
  package.json
  src/controller/index.js
  src/utilities/__snapshots__/utilities.spec.js.snap
  src/utilities/index.js
  src/utilities/utilities.spec.js
Labels: all platforms, bug fix, new feature

#8 Allows scan rate to work properly
  package.json
  src/controller/index.js
Labels: bug fix

#10 Allows leading underscore in tag names
  package.json
  src/tag/index.js
  src/tag/tag.spec.js
Labels: bug fix

#12 Adds the ability to use Fully-Qualified Domain Name for PLC address
  package.json
  src/controller/index.js
  src/enip/index.js
Labels: enhancement, new feature
